export const site = {
  url: "https://neekitasahu.dev",
  name: "Neekita Sahu",
  title: "Neekita Sahu | Fullstack Developer",
  description:
    "Fullstack developer & software engineer building responsive React and Next.js interfaces — scroll-linked motion, SEO that lifted organic traffic 30%, code that ships.",
  role: "Fullstack Developer & Software Engineer",
  email: "neekita635@gmail.com",
  github: "https://github.com/NSDiva",
  linkedin: "https://www.linkedin.com/in/neekita-sahu-3b72a7258/",
  resume: "/Resume_NeekitaSahu.pdf",
  locale: "en_US",
  themeColor: "#0b0b0d",
  accent: "#7CE38B",
  keywords: [
    "Neekita Sahu",
    "Fullstack Developer",
    "Software Engineer",
    "Fullstack Engineer",
    "React Developer",
    "Next.js Developer",
    "React",
    "Next.js",
    "TypeScript",
    "Three.js",
    "Web Developer",
    "Portfolio",
  ],
} as const;
